// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presistence;

#nullable disable

namespace Presistence.Migrations
{
    [DbContext(typeof(IntelliFit_DbContext))]
    [Migration("20251121231030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Models.AIQueryLog", b =>
                {
                    b.Property<int>("QueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueryID"));

                    b.Property<int>("AIAgentAI_ID")
                        .HasColumnType("int");

                    b.Property<int>("AI_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QueryID");

                    b.HasIndex("AIAgentAI_ID");

                    b.HasIndex("UserID");

                    b.ToTable("AIQueryLogs");
                });

            modelBuilder.Entity("DomainLayer.Models.AI_Agent", b =>
                {
                    b.Property<int>("AI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AI_ID"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AI_ID");

                    b.ToTable("AI_Agents");
                });

            modelBuilder.Entity("DomainLayer.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TokensDeducted")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DomainLayer.Models.ChurnPrediction", b =>
                {
                    b.Property<int>("PredictionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionID"));

                    b.Property<float>("ChurnProbability")
                        .HasColumnType("real");

                    b.Property<DateTime>("PredictionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PredictionID");

                    b.HasIndex("UserID");

                    b.ToTable("ChurnPredictions");
                });

            modelBuilder.Entity("DomainLayer.Models.CoachReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<int?>("CoachUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CoachID");

                    b.HasIndex("CoachUserId");

                    b.HasIndex("UserID");

                    b.ToTable("CoachReviews");
                });

            modelBuilder.Entity("DomainLayer.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceIntervalDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TokenCostPerHour")
                        .HasColumnType("int");

                    b.HasKey("EquipmentID");

                    b.HasIndex("AdminUserId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("DomainLayer.Models.EquipmentDemandPrediction", b =>
                {
                    b.Property<int>("PredictionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("DemandScore")
                        .HasColumnType("real");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PredictedForDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PredictionID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("EquipmentDemandPredictions");
                });

            modelBuilder.Entity("DomainLayer.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("DomainLayer.Models.ExerciseFormAnalysis", b =>
                {
                    b.Property<int>("AnalysisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisID"));

                    b.Property<int>("AIAgentAI_ID")
                        .HasColumnType("int");

                    b.Property<int>("AI_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FormScore")
                        .HasColumnType("real");

                    b.Property<float>("InjuryRiskScore")
                        .HasColumnType("real");

                    b.Property<string>("PoseDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepCount")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.HasKey("AnalysisID");

                    b.HasIndex("AIAgentAI_ID");

                    b.HasIndex("SessionID");

                    b.ToTable("ExerciseFormAnalyses");
                });

            modelBuilder.Entity("DomainLayer.Models.GymOccupancy", b =>
                {
                    b.Property<int>("OccupancyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccupancyID"));

                    b.Property<string>("CameraID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OccupancyPercentage")
                        .HasColumnType("real");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccupancyID");

                    b.ToTable("GymOccupancies");
                });

            modelBuilder.Entity("DomainLayer.Models.HeartRateData", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<float>("CaloriesBurned")
                        .HasColumnType("real");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int?>("SessionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("RecordID");

                    b.HasIndex("DeviceID");

                    b.HasIndex("SessionID");

                    b.ToTable("HeartRateData");
                });

            modelBuilder.Entity("DomainLayer.Models.InBodyMeasurement", b =>
                {
                    b.Property<int>("InBodyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InBodyID"));

                    b.Property<string>("AIInsights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BMI")
                        .HasColumnType("real");

                    b.Property<int?>("CoachUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("FatPercentage")
                        .HasColumnType("real");

                    b.Property<float>("MuscleMass")
                        .HasColumnType("real");

                    b.Property<string>("ReceiptPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptionistID")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptionistUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("InBodyID");

                    b.HasIndex("CoachUserId");

                    b.HasIndex("ReceptionistID");

                    b.HasIndex("ReceptionistUserId");

                    b.HasIndex("UserID");

                    b.ToTable("InBodyMeasurements");
                });

            modelBuilder.Entity("DomainLayer.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("int");

                    b.Property<float>("CarbsPer100g")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FatsPer100g")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProteinPer100g")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DomainLayer.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("MaintenanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceID"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DowntimeDays")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("DomainLayer.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<int?>("AddedByCoachID")
                        .HasColumnType("int");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<float>("CarbsGrams")
                        .HasColumnType("real");

                    b.Property<float>("FatsGrams")
                        .HasColumnType("real");

                    b.Property<bool>("IsAddedByCoach")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NutritionPlanId")
                        .HasColumnType("int");

                    b.Property<float>("ProteinGrams")
                        .HasColumnType("real");

                    b.Property<TimeOnly>("RecommendedTime")
                        .HasColumnType("time");

                    b.HasKey("MealId");

                    b.HasIndex("AddedByCoachID");

                    b.HasIndex("NutritionPlanId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("DomainLayer.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealIngredientId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAddedByCoach")
                        .HasColumnType("bit");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedByCoachID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("MealIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.HasIndex("ModifiedByCoachID");

                    b.ToTable("MealIngredients");
                });

            modelBuilder.Entity("DomainLayer.Models.MemberCoachSubscription", b =>
                {
                    b.Property<int>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<int?>("CoachUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionID");

                    b.HasIndex("CoachID");

                    b.HasIndex("CoachUserId");

                    b.HasIndex("UserID");

                    b.ToTable("MemberCoachSubscriptions");
                });

            modelBuilder.Entity("DomainLayer.Models.MemberWorkoutPlan", b =>
                {
                    b.Property<int>("PlanInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanInstanceID"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedByCoachID")
                        .HasColumnType("int");

                    b.Property<int?>("CoachUserId")
                        .HasColumnType("int");

                    b.Property<int>("CompletedWorkouts")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeneratedByAIAI_ID")
                        .HasColumnType("int");

                    b.Property<int?>("GeneratedByAI_ID")
                        .HasColumnType("int");

                    b.Property<int>("PlanSource")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PlanInstanceID");

                    b.HasIndex("AssignedByCoachID");

                    b.HasIndex("CoachUserId");

                    b.HasIndex("GeneratedByAIAI_ID");

                    b.HasIndex("TemplateID");

                    b.HasIndex("UserID");

                    b.ToTable("MemberWorkoutPlans");
                });

            modelBuilder.Entity("DomainLayer.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DomainLayer.Models.NutritionPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<int>("AIAgentAI_ID")
                        .HasColumnType("int");

                    b.Property<int>("AI_ID")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<float>("CarbsGrams")
                        .HasColumnType("real");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("int");

                    b.Property<float>("FatsGrams")
                        .HasColumnType("real");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanSource")
                        .HasColumnType("int");

                    b.Property<float>("ProteinGrams")
                        .HasColumnType("real");

                    b.Property<string>("ReviewComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByCoachID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PlanID");

                    b.HasIndex("AIAgentAI_ID");

                    b.HasIndex("ReviewedByCoachID");

                    b.HasIndex("UserID");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("DomainLayer.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DomainLayer.Models.RecommendedExercise", b =>
                {
                    b.Property<int>("RecommendedExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendedExerciseId"));

                    b.Property<int?>("AddedByCoachID")
                        .HasColumnType("int");

                    b.Property<string>("CoachNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAddedByCoach")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("RestTime")
                        .HasColumnType("time");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.Property<int>("WorkoutRecommendationId")
                        .HasColumnType("int");

                    b.HasKey("RecommendedExerciseId");

                    b.HasIndex("AddedByCoachID");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutRecommendationId");

                    b.ToTable("RecommendedExercises");
                });

            modelBuilder.Entity("DomainLayer.Models.SafetyIncident", b =>
                {
                    b.Property<int>("IncidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("IncidentID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("UserID");

                    b.ToTable("SafetyIncidents");
                });

            modelBuilder.Entity("DomainLayer.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAIFeatures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokensIncluded")
                        .HasColumnType("int");

                    b.HasKey("PlanID");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("DomainLayer.Models.TemplateExercise", b =>
                {
                    b.Property<int>("TemplateExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateExerciseId"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("RestTime")
                        .HasColumnType("time");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("TemplateExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateID");

                    b.ToTable("TemplateExercises");
                });

            modelBuilder.Entity("DomainLayer.Models.TokenTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptionistID")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptionistUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("ReceptionistID");

                    b.HasIndex("ReceptionistUserId");

                    b.HasIndex("UserID");

                    b.ToTable("TokenTransactions");
                });

            modelBuilder.Entity("DomainLayer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitnessGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenBalance")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("UserId");

                    b.HasIndex("AdminUserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DomainLayer.Models.WearableDevice", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PairedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DeviceID");

                    b.HasIndex("UserID");

                    b.ToTable("WearableDevices");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutPlanTemplate", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<int?>("CoachID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("TemplateID");

                    b.HasIndex("CoachID");

                    b.ToTable("WorkoutPlanTemplates");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutRecommendation", b =>
                {
                    b.Property<int>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationID"));

                    b.Property<int>("AIAgentAI_ID")
                        .HasColumnType("int");

                    b.Property<int>("AI_ID")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<int>("PlanSource")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByCoachID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UserResponseAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("RecommendationID");

                    b.HasIndex("AIAgentAI_ID");

                    b.HasIndex("ReviewedByCoachID");

                    b.HasIndex("UserID");

                    b.ToTable("WorkoutRecommendations");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<float?>("AverageHeartRate")
                        .HasColumnType("real");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<int?>("CoachID")
                        .HasColumnType("int");

                    b.Property<int?>("CoachUserId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("IntensityLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsSupervisedByCoach")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("CoachID");

                    b.HasIndex("CoachUserId");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("UserID");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("DomainLayer.Models.Admin", b =>
                {
                    b.HasBaseType("DomainLayer.Models.User");

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("DomainLayer.Models.Coach", b =>
                {
                    b.HasBaseType("DomainLayer.Models.User");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Phone")
                                .HasColumnName("Coach_Phone");
                        });

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("DomainLayer.Models.Receptionist", b =>
                {
                    b.HasBaseType("DomainLayer.Models.User");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptionistID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("DomainLayer.Models.AIQueryLog", b =>
                {
                    b.HasOne("DomainLayer.Models.AI_Agent", "AIAgent")
                        .WithMany("QueryLogs")
                        .HasForeignKey("AIAgentAI_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIAgent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.Booking", b =>
                {
                    b.HasOne("DomainLayer.Models.Equipment", "Equipment")
                        .WithMany("Bookings")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.ChurnPrediction", b =>
                {
                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.CoachReview", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Coach", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CoachUserId");

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.Equipment", b =>
                {
                    b.HasOne("DomainLayer.Models.Admin", null)
                        .WithMany("ManagedEquipment")
                        .HasForeignKey("AdminUserId");
                });

            modelBuilder.Entity("DomainLayer.Models.EquipmentDemandPrediction", b =>
                {
                    b.HasOne("DomainLayer.Models.Equipment", "Equipment")
                        .WithMany("DemandPredictions")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("DomainLayer.Models.ExerciseFormAnalysis", b =>
                {
                    b.HasOne("DomainLayer.Models.AI_Agent", "AIAgent")
                        .WithMany("FormAnalyses")
                        .HasForeignKey("AIAgentAI_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.WorkoutSession", "Session")
                        .WithMany("FormAnalyses")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIAgent");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DomainLayer.Models.HeartRateData", b =>
                {
                    b.HasOne("DomainLayer.Models.WearableDevice", "Device")
                        .WithMany("HeartRateData")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.WorkoutSession", "Session")
                        .WithMany("HeartRateData")
                        .HasForeignKey("SessionID");

                    b.Navigation("Device");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DomainLayer.Models.InBodyMeasurement", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", null)
                        .WithMany("RecordedMeasurements")
                        .HasForeignKey("CoachUserId");

                    b.HasOne("DomainLayer.Models.Receptionist", "Receptionist")
                        .WithMany()
                        .HasForeignKey("ReceptionistID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Receptionist", null)
                        .WithMany("RecordedMeasurements")
                        .HasForeignKey("ReceptionistUserId");

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receptionist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.MaintenanceLog", b =>
                {
                    b.HasOne("DomainLayer.Models.Equipment", "Equipment")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("DomainLayer.Models.Meal", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "AddedByCoach")
                        .WithMany()
                        .HasForeignKey("AddedByCoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByCoach");

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("DomainLayer.Models.MealIngredient", b =>
                {
                    b.HasOne("DomainLayer.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Coach", "ModifiedByCoach")
                        .WithMany()
                        .HasForeignKey("ModifiedByCoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");

                    b.Navigation("ModifiedByCoach");
                });

            modelBuilder.Entity("DomainLayer.Models.MemberCoachSubscription", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Coach", null)
                        .WithMany("HasSubscribers")
                        .HasForeignKey("CoachUserId");

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.MemberWorkoutPlan", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "AssignedByCoach")
                        .WithMany()
                        .HasForeignKey("AssignedByCoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.Coach", null)
                        .WithMany("AssignedPlans")
                        .HasForeignKey("CoachUserId");

                    b.HasOne("DomainLayer.Models.AI_Agent", "GeneratedByAI")
                        .WithMany()
                        .HasForeignKey("GeneratedByAIAI_ID");

                    b.HasOne("DomainLayer.Models.WorkoutPlanTemplate", "Template")
                        .WithMany("MemberPlans")
                        .HasForeignKey("TemplateID");

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByCoach");

                    b.Navigation("GeneratedByAI");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.Notification", b =>
                {
                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.NutritionPlan", b =>
                {
                    b.HasOne("DomainLayer.Models.AI_Agent", "AIAgent")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("AIAgentAI_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Coach", "ReviewedByCoach")
                        .WithMany()
                        .HasForeignKey("ReviewedByCoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIAgent");

                    b.Navigation("ReviewedByCoach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.Payment", b =>
                {
                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.RecommendedExercise", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "AddedByCoach")
                        .WithMany()
                        .HasForeignKey("AddedByCoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.WorkoutRecommendation", "WorkoutRecommendation")
                        .WithMany("RecommendedExercises")
                        .HasForeignKey("WorkoutRecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByCoach");

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutRecommendation");
                });

            modelBuilder.Entity("DomainLayer.Models.SafetyIncident", b =>
                {
                    b.HasOne("DomainLayer.Models.Equipment", "Equipment")
                        .WithMany("SafetyIncidents")
                        .HasForeignKey("EquipmentID");

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.TemplateExercise", b =>
                {
                    b.HasOne("DomainLayer.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.WorkoutPlanTemplate", "Template")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DomainLayer.Models.TokenTransaction", b =>
                {
                    b.HasOne("DomainLayer.Models.Receptionist", "Receptionist")
                        .WithMany()
                        .HasForeignKey("ReceptionistID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.Receptionist", null)
                        .WithMany("ProcessedTransactions")
                        .HasForeignKey("ReceptionistUserId");

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receptionist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.User", b =>
                {
                    b.HasOne("DomainLayer.Models.Admin", null)
                        .WithMany("ManagedUsers")
                        .HasForeignKey("AdminUserId");
                });

            modelBuilder.Entity("DomainLayer.Models.WearableDevice", b =>
                {
                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutPlanTemplate", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "Coach")
                        .WithMany("CreatedTemplates")
                        .HasForeignKey("CoachID");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutRecommendation", b =>
                {
                    b.HasOne("DomainLayer.Models.AI_Agent", "AIAgent")
                        .WithMany("Recommendations")
                        .HasForeignKey("AIAgentAI_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.Coach", "ReviewedByCoach")
                        .WithMany()
                        .HasForeignKey("ReviewedByCoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIAgent");

                    b.Navigation("ReviewedByCoach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutSession", b =>
                {
                    b.HasOne("DomainLayer.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DomainLayer.Models.Coach", null)
                        .WithMany("SupervisedSessions")
                        .HasForeignKey("CoachUserId");

                    b.HasOne("DomainLayer.Models.Equipment", "Equipment")
                        .WithMany("UsedInSessions")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Models.AI_Agent", b =>
                {
                    b.Navigation("FormAnalyses");

                    b.Navigation("NutritionPlans");

                    b.Navigation("QueryLogs");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("DomainLayer.Models.Equipment", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("DemandPredictions");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("SafetyIncidents");

                    b.Navigation("UsedInSessions");
                });

            modelBuilder.Entity("DomainLayer.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("DomainLayer.Models.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DomainLayer.Models.NutritionPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("DomainLayer.Models.WearableDevice", b =>
                {
                    b.Navigation("HeartRateData");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutPlanTemplate", b =>
                {
                    b.Navigation("MemberPlans");

                    b.Navigation("TemplateExercises");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutRecommendation", b =>
                {
                    b.Navigation("RecommendedExercises");
                });

            modelBuilder.Entity("DomainLayer.Models.WorkoutSession", b =>
                {
                    b.Navigation("FormAnalyses");

                    b.Navigation("HeartRateData");
                });

            modelBuilder.Entity("DomainLayer.Models.Admin", b =>
                {
                    b.Navigation("ManagedEquipment");

                    b.Navigation("ManagedUsers");
                });

            modelBuilder.Entity("DomainLayer.Models.Coach", b =>
                {
                    b.Navigation("AssignedPlans");

                    b.Navigation("CreatedTemplates");

                    b.Navigation("HasSubscribers");

                    b.Navigation("RecordedMeasurements");

                    b.Navigation("Reviews");

                    b.Navigation("SupervisedSessions");
                });

            modelBuilder.Entity("DomainLayer.Models.Receptionist", b =>
                {
                    b.Navigation("ProcessedTransactions");

                    b.Navigation("RecordedMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
